////

    Copyright 2006-2017 the original author or authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

////
= Acknowledgements

Objenesis was not written from scratch. It was the result of spotting duplication amongst
other open source projects that were doing similar things and creating a best-of-breed solution.

Code from Objenesis was adapted from code from these projects:

* http://x-stream.github.io[XStream]
* http://jserial.sourceforge.net[JSerial]
* http://easymock.org[EasyMock]

== Development Team

* *Joe Walnes*
* *Henri Tremblay*
* *Leonardo Mesquita*

To contact the developers, please use the link:support.html[discussion group].

== Contributors

* Chris Nokleberg (determined how to http://sixlegs.com/blog/java/skipping-constructors.html[construct a byte sequence to deserialize an object])
* Nat Pryce (researched http://jmock.org/[web site design] that this site is based upon)
* Henrik St&aring;hl (from http://www.bea.com[BEA]) for helping with JRockit support
* Ian Parkinson (from http://www.google.com[Google]) for providing the Dalvik support
* Piotr 'Qertoip' W&#322;odarek for providing Gingerbread support

== Supporting Services

* Code hosted by https://github.com/easymock/objenesis[GitHub].
* Mailing list hosted by http://groups.google.com[Google Groups].
* Benchmarking done using http://openjdk.java.net/projects/code-tools/jmh[JMH].
* Embeddable library thanks to https://code.google.com/p/jarjar/[Jar Jar Links] and http://maven.apache.org/plugins/maven-shade-plugin[Maven shade plugin].
* Site generation using http://asciidoctor.org[AsciiDoc].
* Logo by http://cooltext.com[Cool Text].
