////

    Copyright 2006-2017 the original author or authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

////
= Download

Current version is *${project-version}*

* https://bintray.com/artifact/download/easymock/distributions/objenesis-${project-version}-bin.zip[*objenesis-${project.version}-bin.zip*] - Objenesis distribution (binaries, sources and javadoc).
* https://bintray.com/artifact/download/easymock/distributions/objenesis-tck-${project-version}.jar[*objenesis-tck-${project.version}.jar*] - TCK to test your environment. See link:details.html[details].
* https://bintray.com/artifact/download/easymock/distributions/objenesis-tck-android-${project-version}.apk[*objenesis-tck-android-${project.version}.apk*] - Android TCK to test your Dalvik version. See <a href="details.html">details</a>.

Older versions can be found https://bintray.com/easymock/distributions/objenesis[here]
