////

    Copyright 2006-2017 the original author or authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

////
= Twenty Second Tutorial

There are two main interfaces in Objenesis:

* *${javadoc}/org/objenesis/instantiator/ObjectInstantiator.html[ObjectInstantiator]*
** Instantiates multiple instances of a single class.
[source,java]
----
interface ObjectInstantiator {
  Object newInstance();
}
* *${javadoc}/org/objenesis/strategy/InstantiatorStrategy.html[InstantiatorStrategy]*
** A particular strategy for how to instantiate a class (as this differs for different types of classes).
[source,java]
----
interface InstantiatorStrategy {
  ObjectInstantiator newInstantiatorOf(Class type);
}

*Note:* All Objenesis classes are in the `org.objenesis` package.

== Step By Step

There are many different strategies that Objenesis uses for instantiating objects based on the JVM vendor,
JVM version, SecurityManager and type of class being instantiated.

We have defined that two different kinds of instantiation are required:

* *Stardard* - No constructor will be called
* *Serializable compliant* - Acts like an object instantiated by java standard serialization. It means that the
constructor of the first non-serializable parent class will be called. However, readResolve is not called and
we never check if the object is serializable.

The simplest way to use Objenesis is by using ${javadoc}/org/objenesis/ObjenesisStd.html[ObjenesisStd] (Standard) and
${javadoc}/org/objenesis/ObjenesisSerializer.html[ObjenesisSerializer] (Serializable compliant). By default,
automatically determines the best strategy - so you don't have to.

[source,java]
----
Objenesis objenesis = new ObjenesisStd(); // or ObjenesisSerializer
----

Once you have the Objenesis implementation, you can then create an `ObjectInstantiator`, for a specific type.

[source,java]
----
ObjectInstantiator thingyInstantiator = objenesis.getInstantiatorOf(MyThingy.class);
----

Finally, you can use this to instantiate new instances of this type.

[source,java]
----
MyThingy thingy1 = (MyThingy)thingyInstantiator.newInstance();
MyThingy thingy2 = (MyThingy)thingyInstantiator.newInstance();
MyThingy thingy3 = (MyThingy)thingyInstantiator.newInstance();
----

== Performance and Threading

To improve performance, it is best to reuse the `ObjectInstantiator`
objects as much as possible. For example, if you are instantiating multiple instances of a specific class,
do it from the same `ObjectInstantiator`.

Both `InstantiatorStrategy` and `ObjectInstantiator` can be shared between multiple
threads and used concurrently. They are thread safe.

== That Code Again

(For the impatient)

[source,java]
----
Objenesis objenesis = new ObjenesisStd(); // or ObjenesisSerializer
MyThingy thingy1 = (MyThingy) objenesis.newInstance(MyThingy.class);

// or (a little bit more efficient if you need to create many objects)

Objenesis objenesis = new ObjenesisStd(); // or ObjenesisSerializer
ObjectInstantiator thingyInstantiator = objenesis.getInstantiatorOf(MyThingy.class);

MyThingy thingy2 = (MyThingy)thingyInstantiator.newInstance();
MyThingy thingy3 = (MyThingy)thingyInstantiator.newInstance();
MyThingy thingy4 = (MyThingy)thingyInstantiator.newInstance();
----
